apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
spec:
  serviceName: mysql
  replicas: 4
  selector:
    matchLabels:
      app: mysql # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: mysql # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:latest
        env:
         - name: MYSQL_ROOT_PASSWORD
           value: "your-root-password"
         - name: MYSQL_DATABASE  
           value: "tower-01"
         - name: MYSQL_USERNAME  
           value: "tower"
         - name: MYSQL_PASSWORD  
           value: "your-password"    

